# Form implementation generated from reading ui file 'UI_Main.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EasyConnectACAD(object):
    def setupUi(self, EasyConnectACAD):
        EasyConnectACAD.setObjectName("EasyConnectACAD")
        EasyConnectACAD.resize(1424, 887)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EasyConnectACAD.sizePolicy().hasHeightForWidth())
        EasyConnectACAD.setSizePolicy(sizePolicy)
        EasyConnectACAD.setMinimumSize(QtCore.QSize(1424, 887))
        EasyConnectACAD.setMaximumSize(QtCore.QSize(16777215, 16777215))
        EasyConnectACAD.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/scale.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        EasyConnectACAD.setWindowIcon(icon)
        EasyConnectACAD.setStyleSheet("\n"
"background-color: rgb(54, 58, 69);\n"
"")
        EasyConnectACAD.setDocumentMode(False)
        EasyConnectACAD.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=EasyConnectACAD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_25.setContentsMargins(10, 8, 10, 0)
        self.gridLayout_25.setSpacing(0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_footer = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_footer.setFont(font)
        self.label_footer.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_footer.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_footer.setObjectName("label_footer")
        self.gridLayout_25.addWidget(self.label_footer, 2, 0, 1, 1)
        self.FRAME_EasyConnect = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FRAME_EasyConnect.sizePolicy().hasHeightForWidth())
        self.FRAME_EasyConnect.setSizePolicy(sizePolicy)
        self.FRAME_EasyConnect.setMinimumSize(QtCore.QSize(0, 77))
        self.FRAME_EasyConnect.setMaximumSize(QtCore.QSize(16777215, 77))
        self.FRAME_EasyConnect.setStyleSheet("QFrame {\n"
"    border-radius: 15px; /* Slightly rounded corners */\n"
" \n"
"background-color: rgb(30, 40, 49);\n"
"    color: (0,0,0);     \n"
"}\n"
"QLabel {\n"
"    color: black; /* Set text color */\n"
"\n"
"}\n"
"")
        self.FRAME_EasyConnect.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.FRAME_EasyConnect.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_EasyConnect.setObjectName("FRAME_EasyConnect")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.FRAME_EasyConnect)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_TITLE_EasyConnect = QtWidgets.QLabel(parent=self.FRAME_EasyConnect)
        self.label_TITLE_EasyConnect.setStyleSheet("")
        self.label_TITLE_EasyConnect.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_TITLE_EasyConnect.setObjectName("label_TITLE_EasyConnect")
        self.gridLayout_15.addWidget(self.label_TITLE_EasyConnect, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.FRAME_EasyConnect, 0, 0, 1, 1)
        self.Main_frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_frame.sizePolicy().hasHeightForWidth())
        self.Main_frame.setSizePolicy(sizePolicy)
        self.Main_frame.setStyleSheet("background-color: rgb(54, 58, 69);")
        self.Main_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Main_frame.setObjectName("Main_frame")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.Main_frame)
        self.gridLayout_23.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.tab_main_widget = QtWidgets.QTabWidget(parent=self.Main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_main_widget.sizePolicy().hasHeightForWidth())
        self.tab_main_widget.setSizePolicy(sizePolicy)
        self.tab_main_widget.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tab_main_widget.setStyleSheet("\n"
"\n"
"QTabBar::tab:selected {\n"
"color: rgb(0, 0, 0);\n"
"    background-color: #444; /* Slightly lighter background for selected tab */\n"
"    \n"
"}\n"
"\n"
"\n"
"QScrollBar\n"
"{\n"
"background : rgb(203, 210, 255);;\n"
"}\n"
"QScrollBar::handle\n"
"{\n"
"    background-color:  rgb(52, 53, 65);\n"
"}\n"
"QScrollBar::handle::pressed\n"
"{\n"
"background-color: red;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: None\n"
"  }\n"
"")
        self.tab_main_widget.setIconSize(QtCore.QSize(25, 25))
        self.tab_main_widget.setUsesScrollButtons(False)
        self.tab_main_widget.setDocumentMode(False)
        self.tab_main_widget.setTabsClosable(False)
        self.tab_main_widget.setMovable(False)
        self.tab_main_widget.setTabBarAutoHide(False)
        self.tab_main_widget.setObjectName("tab_main_widget")
        self.tabTransformer = QtWidgets.QWidget()
        self.tabTransformer.setObjectName("tabTransformer")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabTransformer)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.output_CT_ScrollArea = QtWidgets.QScrollArea(parent=self.tabTransformer)
        self.output_CT_ScrollArea.setWidgetResizable(True)
        self.output_CT_ScrollArea.setObjectName("output_CT_ScrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 688, 655))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.output_CT_ScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_7.addWidget(self.output_CT_ScrollArea, 0, 1, 1, 1)
        self.input_CT_ScrollArea = QtWidgets.QScrollArea(parent=self.tabTransformer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_CT_ScrollArea.sizePolicy().hasHeightForWidth())
        self.input_CT_ScrollArea.setSizePolicy(sizePolicy)
        self.input_CT_ScrollArea.setMinimumSize(QtCore.QSize(690, 0))
        self.input_CT_ScrollArea.setMaximumSize(QtCore.QSize(690, 16777215))
        self.input_CT_ScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.input_CT_ScrollArea.setWidgetResizable(True)
        self.input_CT_ScrollArea.setObjectName("input_CT_ScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -279, 673, 936))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.FRAME_HV_CT = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FRAME_HV_CT.sizePolicy().hasHeightForWidth())
        self.FRAME_HV_CT.setSizePolicy(sizePolicy)
        self.FRAME_HV_CT.setMinimumSize(QtCore.QSize(0, 0))
        self.FRAME_HV_CT.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FRAME_HV_CT.setStyleSheet("background-color: rgb(30, 40, 49);\n"
"color: rgb(0, 0, 0);")
        self.FRAME_HV_CT.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.FRAME_HV_CT.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.FRAME_HV_CT.setObjectName("FRAME_HV_CT")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.FRAME_HV_CT)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.i_CTH1_accuracy_override = QtWidgets.QLineEdit(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_CTH1_accuracy_override.sizePolicy().hasHeightForWidth())
        self.i_CTH1_accuracy_override.setSizePolicy(sizePolicy)
        self.i_CTH1_accuracy_override.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_CTH1_accuracy_override.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_CTH1_accuracy_override.setText("")
        self.i_CTH1_accuracy_override.setFrame(False)
        self.i_CTH1_accuracy_override.setObjectName("i_CTH1_accuracy_override")
        self.gridLayout_2.addWidget(self.i_CTH1_accuracy_override, 11, 3, 1, 1)
        self.frame_packings = QtWidgets.QFrame(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_packings.sizePolicy().hasHeightForWidth())
        self.frame_packings.setSizePolicy(sizePolicy)
        self.frame_packings.setStyleSheet("QFrame {\n"
"    border-radius: 6px; /* Slightly rounded corners */\n"
" \n"
"    background-color: transparent; /* Keeps original background */\n"
"    color: (0,0,0);     \n"
"}\n"
"QLabel {\n"
"    color: black; /* Set text color */\n"
"\n"
"}\n"
"")
        self.frame_packings.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_packings.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_packings.setObjectName("frame_packings")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_packings)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addWidget(self.frame_packings, 11, 5, 1, 1)
        self.box_CTH1_Application = QtWidgets.QComboBox(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_CTH1_Application.sizePolicy().hasHeightForWidth())
        self.box_CTH1_Application.setSizePolicy(sizePolicy)
        self.box_CTH1_Application.setMinimumSize(QtCore.QSize(0, 0))
        self.box_CTH1_Application.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.box_CTH1_Application.setFont(font)
        self.box_CTH1_Application.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.box_CTH1_Application.setAcceptDrops(False)
        self.box_CTH1_Application.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.box_CTH1_Application.setAutoFillBackground(False)
        self.box_CTH1_Application.setStyleSheet("QComboBox {\n"
"                font-size: 10px;\n"
"         \n"
"                color: white;\n"
"                background: rgba(50, 50, 50, 0.8);\n"
"                border-radius: 10px;\n"
"                padding: 5px;\n"
"            }\n"
"            QComboBox::drop-down {\n"
"                border: none;\n"
"                background: transparent;\n"
"            }\n"
"            QComboBox QAbstractItemView {\n"
"                background: #2E2E2E;\n"
"                selection-background-color: #00BCD4;\n"
"                selection-color: white;\n"
"            }\n"
"            QComboBox:hover {\n"
"                background: rgba(80, 80, 80, 0.9);\n"
"                border-color: #03A9F4;\n"
"            }\n"
"            QComboBox:on {\n"
"                background: rgba(30, 30, 30, 0.9);\n"
"                border-color: #0288D1;\n"
"            }")
        self.box_CTH1_Application.setEditable(False)
        self.box_CTH1_Application.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtCurrent)
        self.box_CTH1_Application.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.box_CTH1_Application.setFrame(False)
        self.box_CTH1_Application.setObjectName("box_CTH1_Application")
        self.box_CTH1_Application.addItem("")
        self.box_CTH1_Application.addItem("")
        self.box_CTH1_Application.addItem("")
        self.gridLayout_2.addWidget(self.box_CTH1_Application, 2, 3, 1, 1)
        self.box_CTH1_bushing_angled = QtWidgets.QComboBox(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_CTH1_bushing_angled.sizePolicy().hasHeightForWidth())
        self.box_CTH1_bushing_angled.setSizePolicy(sizePolicy)
        self.box_CTH1_bushing_angled.setMinimumSize(QtCore.QSize(0, 0))
        self.box_CTH1_bushing_angled.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.box_CTH1_bushing_angled.setFont(font)
        self.box_CTH1_bushing_angled.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.box_CTH1_bushing_angled.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.box_CTH1_bushing_angled.setStyleSheet("QComboBox {\n"
"                font-size: 10px;\n"
"         \n"
"                color: white;\n"
"                background: rgba(50, 50, 50, 0.8);\n"
"                border-radius: 10px;\n"
"                padding: 5px;\n"
"            }\n"
"            QComboBox::drop-down {\n"
"                border: none;\n"
"                background: transparent;\n"
"            }\n"
"            QComboBox QAbstractItemView {\n"
"                background: #2E2E2E;\n"
"                selection-background-color: #00BCD4;\n"
"                selection-color: white;\n"
"            }\n"
"            QComboBox:hover {\n"
"                background: rgba(80, 80, 80, 0.9);\n"
"                border-color: #03A9F4;\n"
"            }\n"
"            QComboBox:on {\n"
"                background: rgba(30, 30, 30, 0.9);\n"
"                border-color: #0288D1;\n"
"            }")
        self.box_CTH1_bushing_angled.setEditable(False)
        self.box_CTH1_bushing_angled.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtCurrent)
        self.box_CTH1_bushing_angled.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.box_CTH1_bushing_angled.setFrame(False)
        self.box_CTH1_bushing_angled.setObjectName("box_CTH1_bushing_angled")
        self.box_CTH1_bushing_angled.addItem("")
        self.box_CTH1_bushing_angled.addItem("")
        self.gridLayout_2.addWidget(self.box_CTH1_bushing_angled, 5, 3, 1, 1)
        self.label_CT_Type = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_CT_Type.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_CT_Type.setObjectName("label_CT_Type")
        self.gridLayout_2.addWidget(self.label_CT_Type, 3, 0, 1, 1)
        self.label_Bushing_Angled = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_Bushing_Angled.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Bushing_Angled.setObjectName("label_Bushing_Angled")
        self.gridLayout_2.addWidget(self.label_Bushing_Angled, 5, 0, 1, 1)
        self.label_CT_Application = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_CT_Application.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_CT_Application.setObjectName("label_CT_Application")
        self.gridLayout_2.addWidget(self.label_CT_Application, 2, 0, 1, 1)
        self.label_Tag_Individual = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_Tag_Individual.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Tag_Individual.setObjectName("label_Tag_Individual")
        self.gridLayout_2.addWidget(self.label_Tag_Individual, 7, 0, 1, 1)
        self.label_Bushing_OD = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_Bushing_OD.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Bushing_OD.setObjectName("label_Bushing_OD")
        self.gridLayout_2.addWidget(self.label_Bushing_OD, 4, 0, 1, 1)
        self.label_Thermal_Factor = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_Thermal_Factor.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Thermal_Factor.setObjectName("label_Thermal_Factor")
        self.gridLayout_2.addWidget(self.label_Thermal_Factor, 15, 0, 1, 3)
        self.i_CTH1_thermal_factor = QtWidgets.QLineEdit(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_CTH1_thermal_factor.sizePolicy().hasHeightForWidth())
        self.i_CTH1_thermal_factor.setSizePolicy(sizePolicy)
        self.i_CTH1_thermal_factor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_CTH1_thermal_factor.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_CTH1_thermal_factor.setText("")
        self.i_CTH1_thermal_factor.setFrame(False)
        self.i_CTH1_thermal_factor.setObjectName("i_CTH1_thermal_factor")
        self.gridLayout_2.addWidget(self.i_CTH1_thermal_factor, 15, 3, 1, 1)
        self.label_Ratio_Override = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_Ratio_Override.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Ratio_Override.setObjectName("label_Ratio_Override")
        self.gridLayout_2.addWidget(self.label_Ratio_Override, 9, 0, 1, 1)
        self.label_CT_Height_Override = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_CT_Height_Override.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_CT_Height_Override.setObjectName("label_CT_Height_Override")
        self.gridLayout_2.addWidget(self.label_CT_Height_Override, 8, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 16, 3, 1, 3)
        self.label_Ratio_Type = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_Ratio_Type.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Ratio_Type.setObjectName("label_Ratio_Type")
        self.gridLayout_2.addWidget(self.label_Ratio_Type, 14, 0, 1, 1)
        self.tableCTHigh = QtWidgets.QTableWidget(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableCTHigh.sizePolicy().hasHeightForWidth())
        self.tableCTHigh.setSizePolicy(sizePolicy)
        self.tableCTHigh.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableCTHigh.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableCTHigh.setGridStyle(QtCore.Qt.PenStyle.DashLine)
        self.tableCTHigh.setObjectName("tableCTHigh")
        self.tableCTHigh.setColumnCount(4)
        self.tableCTHigh.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCTHigh.setItem(0, 3, item)
        self.tableCTHigh.horizontalHeader().setVisible(True)
        self.tableCTHigh.horizontalHeader().setCascadingSectionResizes(False)
        self.tableCTHigh.horizontalHeader().setSortIndicatorShown(False)
        self.tableCTHigh.horizontalHeader().setStretchLastSection(False)
        self.tableCTHigh.verticalHeader().setVisible(True)
        self.tableCTHigh.verticalHeader().setCascadingSectionResizes(False)
        self.tableCTHigh.verticalHeader().setHighlightSections(True)
        self.tableCTHigh.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout_2.addWidget(self.tableCTHigh, 7, 3, 1, 3)
        self.label_Accuracy_Override = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_Accuracy_Override.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Accuracy_Override.setObjectName("label_Accuracy_Override")
        self.gridLayout_2.addWidget(self.label_Accuracy_Override, 11, 0, 1, 1)
        self.i_CTH1_ratio_type = QtWidgets.QLineEdit(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_CTH1_ratio_type.sizePolicy().hasHeightForWidth())
        self.i_CTH1_ratio_type.setSizePolicy(sizePolicy)
        self.i_CTH1_ratio_type.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_CTH1_ratio_type.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_CTH1_ratio_type.setText("")
        self.i_CTH1_ratio_type.setFrame(False)
        self.i_CTH1_ratio_type.setObjectName("i_CTH1_ratio_type")
        self.gridLayout_2.addWidget(self.i_CTH1_ratio_type, 14, 3, 1, 1)
        self.i_CTH1_height_override = QtWidgets.QLineEdit(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_CTH1_height_override.sizePolicy().hasHeightForWidth())
        self.i_CTH1_height_override.setSizePolicy(sizePolicy)
        self.i_CTH1_height_override.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_CTH1_height_override.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_CTH1_height_override.setText("")
        self.i_CTH1_height_override.setFrame(False)
        self.i_CTH1_height_override.setObjectName("i_CTH1_height_override")
        self.gridLayout_2.addWidget(self.i_CTH1_height_override, 8, 3, 1, 1)
        self.i_Bushing_OD = QtWidgets.QLineEdit(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_Bushing_OD.sizePolicy().hasHeightForWidth())
        self.i_Bushing_OD.setSizePolicy(sizePolicy)
        self.i_Bushing_OD.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_Bushing_OD.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_Bushing_OD.setFrame(False)
        self.i_Bushing_OD.setObjectName("i_Bushing_OD")
        self.gridLayout_2.addWidget(self.i_Bushing_OD, 4, 3, 1, 1)
        self.i_CTH1_ratio_override = QtWidgets.QLineEdit(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_CTH1_ratio_override.sizePolicy().hasHeightForWidth())
        self.i_CTH1_ratio_override.setSizePolicy(sizePolicy)
        self.i_CTH1_ratio_override.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_CTH1_ratio_override.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_CTH1_ratio_override.setText("")
        self.i_CTH1_ratio_override.setFrame(False)
        self.i_CTH1_ratio_override.setObjectName("i_CTH1_ratio_override")
        self.gridLayout_2.addWidget(self.i_CTH1_ratio_override, 9, 3, 1, 1)
        self.box_CTH1_Type = QtWidgets.QComboBox(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_CTH1_Type.sizePolicy().hasHeightForWidth())
        self.box_CTH1_Type.setSizePolicy(sizePolicy)
        self.box_CTH1_Type.setMinimumSize(QtCore.QSize(0, 0))
        self.box_CTH1_Type.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.box_CTH1_Type.setFont(font)
        self.box_CTH1_Type.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.box_CTH1_Type.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.box_CTH1_Type.setStyleSheet("QComboBox {\n"
"                font-size: 10px;\n"
"         \n"
"                color: white;\n"
"                background: rgba(50, 50, 50, 0.8);\n"
"                border-radius: 10px;\n"
"                padding: 5px;\n"
"            }\n"
"            QComboBox::drop-down {\n"
"                border: none;\n"
"                background: transparent;\n"
"            }\n"
"            QComboBox QAbstractItemView {\n"
"                background: #2E2E2E;\n"
"                selection-background-color: #00BCD4;\n"
"                selection-color: white;\n"
"            }\n"
"            QComboBox:hover {\n"
"                background: rgba(80, 80, 80, 0.9);\n"
"                border-color: #03A9F4;\n"
"            }\n"
"            QComboBox:on {\n"
"                background: rgba(30, 30, 30, 0.9);\n"
"                border-color: #0288D1;\n"
"            }")
        self.box_CTH1_Type.setEditable(False)
        self.box_CTH1_Type.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtCurrent)
        self.box_CTH1_Type.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.box_CTH1_Type.setFrame(False)
        self.box_CTH1_Type.setObjectName("box_CTH1_Type")
        self.box_CTH1_Type.addItem("")
        self.box_CTH1_Type.addItem("")
        self.gridLayout_2.addWidget(self.box_CTH1_Type, 3, 3, 1, 1)
        self.picture_Frame = QtWidgets.QFrame(parent=self.FRAME_HV_CT)
        self.picture_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.picture_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.picture_Frame.setObjectName("picture_Frame")
        self.gridLayout_2.addWidget(self.picture_Frame, 1, 4, 6, 2)
        self.label_STD = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_STD.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_STD.setObjectName("label_STD")
        self.gridLayout_2.addWidget(self.label_STD, 6, 0, 1, 1)
        self.label_Notes = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_Notes.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Notes.setObjectName("label_Notes")
        self.gridLayout_2.addWidget(self.label_Notes, 16, 0, 1, 3)
        self.box_CTH1_STD = QtWidgets.QComboBox(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_CTH1_STD.sizePolicy().hasHeightForWidth())
        self.box_CTH1_STD.setSizePolicy(sizePolicy)
        self.box_CTH1_STD.setMinimumSize(QtCore.QSize(0, 0))
        self.box_CTH1_STD.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.box_CTH1_STD.setFont(font)
        self.box_CTH1_STD.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.box_CTH1_STD.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.box_CTH1_STD.setStyleSheet("QComboBox {\n"
"                font-size: 10px;\n"
"         \n"
"                color: white;\n"
"                background: rgba(50, 50, 50, 0.8);\n"
"                border-radius: 10px;\n"
"                padding: 5px;\n"
"            }\n"
"            QComboBox::drop-down {\n"
"                border: none;\n"
"                background: transparent;\n"
"            }\n"
"            QComboBox QAbstractItemView {\n"
"                background: #2E2E2E;\n"
"                selection-background-color: #00BCD4;\n"
"                selection-color: white;\n"
"            }\n"
"            QComboBox:hover {\n"
"                background: rgba(80, 80, 80, 0.9);\n"
"                border-color: #03A9F4;\n"
"            }\n"
"            QComboBox:on {\n"
"                background: rgba(30, 30, 30, 0.9);\n"
"                border-color: #0288D1;\n"
"            }")
        self.box_CTH1_STD.setEditable(False)
        self.box_CTH1_STD.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtCurrent)
        self.box_CTH1_STD.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.box_CTH1_STD.setFrame(False)
        self.box_CTH1_STD.setObjectName("box_CTH1_STD")
        self.box_CTH1_STD.addItem("")
        self.box_CTH1_STD.addItem("")
        self.box_CTH1_STD.addItem("")
        self.gridLayout_2.addWidget(self.box_CTH1_STD, 6, 3, 1, 1)
        self.label_Tag = QtWidgets.QLabel(parent=self.FRAME_HV_CT)
        self.label_Tag.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Tag.setObjectName("label_Tag")
        self.gridLayout_2.addWidget(self.label_Tag, 1, 0, 1, 1)
        self.i_CTH1_tag = QtWidgets.QLineEdit(parent=self.FRAME_HV_CT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_CTH1_tag.sizePolicy().hasHeightForWidth())
        self.i_CTH1_tag.setSizePolicy(sizePolicy)
        self.i_CTH1_tag.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_CTH1_tag.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_CTH1_tag.setFrame(False)
        self.i_CTH1_tag.setObjectName("i_CTH1_tag")
        self.gridLayout_2.addWidget(self.i_CTH1_tag, 1, 3, 1, 1)
        self.gridLayout_3.addWidget(self.FRAME_HV_CT, 6, 0, 1, 1)
        self.title_General_Info = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_General_Info.sizePolicy().hasHeightForWidth())
        self.title_General_Info.setSizePolicy(sizePolicy)
        self.title_General_Info.setMinimumSize(QtCore.QSize(0, 19))
        self.title_General_Info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.title_General_Info.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.title_General_Info.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.title_General_Info.setScaledContents(False)
        self.title_General_Info.setWordWrap(False)
        self.title_General_Info.setObjectName("title_General_Info")
        self.gridLayout_3.addWidget(self.title_General_Info, 0, 0, 1, 1)
        self.title_CTH_INPUTS = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_CTH_INPUTS.sizePolicy().hasHeightForWidth())
        self.title_CTH_INPUTS.setSizePolicy(sizePolicy)
        self.title_CTH_INPUTS.setMinimumSize(QtCore.QSize(0, 19))
        self.title_CTH_INPUTS.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.title_CTH_INPUTS.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.title_CTH_INPUTS.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.title_CTH_INPUTS.setScaledContents(False)
        self.title_CTH_INPUTS.setWordWrap(False)
        self.title_CTH_INPUTS.setObjectName("title_CTH_INPUTS")
        self.gridLayout_3.addWidget(self.title_CTH_INPUTS, 3, 0, 1, 1)
        self.FRAME_GENERAL = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FRAME_GENERAL.sizePolicy().hasHeightForWidth())
        self.FRAME_GENERAL.setSizePolicy(sizePolicy)
        self.FRAME_GENERAL.setMinimumSize(QtCore.QSize(0, 0))
        self.FRAME_GENERAL.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FRAME_GENERAL.setStyleSheet("\n"
"\n"
"QFrame{\n"
"    background-color: rgb(30, 40, 49);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    padding: 20px 10px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(30, 40, 49);\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}\n"
"")
        self.FRAME_GENERAL.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.FRAME_GENERAL.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.FRAME_GENERAL.setObjectName("FRAME_GENERAL")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.FRAME_GENERAL)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.run_button = QtWidgets.QPushButton(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_button.sizePolicy().hasHeightForWidth())
        self.run_button.setSizePolicy(sizePolicy)
        self.run_button.setMinimumSize(QtCore.QSize(100, 0))
        self.run_button.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.run_button.setToolTip("")
        self.run_button.setStyleSheet("background-image: url(:/icons/icons/cil-library-add.png);\n"
"background-repeat: none;\n"
"\n"
"background-position: center ;\n"
"\n"
"QPushButton{\n"
"    padding: 20px 10px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: #005500;\n"
"    color: #005500;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.run_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.run_button.setIcon(icon1)
        self.run_button.setIconSize(QtCore.QSize(25, 25))
        self.run_button.setAutoRepeatDelay(300)
        self.run_button.setObjectName("run_button")
        self.gridLayout_4.addWidget(self.run_button, 14, 2, 1, 1)
        self.box_Cooling_Class = QtWidgets.QComboBox(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_Cooling_Class.sizePolicy().hasHeightForWidth())
        self.box_Cooling_Class.setSizePolicy(sizePolicy)
        self.box_Cooling_Class.setMinimumSize(QtCore.QSize(0, 0))
        self.box_Cooling_Class.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.box_Cooling_Class.setFont(font)
        self.box_Cooling_Class.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.box_Cooling_Class.setAcceptDrops(False)
        self.box_Cooling_Class.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.box_Cooling_Class.setAutoFillBackground(False)
        self.box_Cooling_Class.setStyleSheet("QComboBox {\n"
"                font-size: 10px;\n"
"         \n"
"                color: white;\n"
"                background: rgba(50, 50, 50, 0.8);\n"
"                border-radius: 10px;\n"
"                padding: 5px;\n"
"            }\n"
"            QComboBox::drop-down {\n"
"                border: none;\n"
"                background: transparent;\n"
"            }\n"
"            QComboBox QAbstractItemView {\n"
"                background: #2E2E2E;\n"
"                selection-background-color: #00BCD4;\n"
"                selection-color: white;\n"
"            }\n"
"            QComboBox:hover {\n"
"                background: rgba(80, 80, 80, 0.9);\n"
"                border-color: #03A9F4;\n"
"            }\n"
"            QComboBox:on {\n"
"                background: rgba(30, 30, 30, 0.9);\n"
"                border-color: #0288D1;\n"
"            }")
        self.box_Cooling_Class.setEditable(False)
        self.box_Cooling_Class.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtCurrent)
        self.box_Cooling_Class.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.box_Cooling_Class.setFrame(False)
        self.box_Cooling_Class.setObjectName("box_Cooling_Class")
        self.box_Cooling_Class.addItem("")
        self.box_Cooling_Class.addItem("")
        self.box_Cooling_Class.addItem("")
        self.gridLayout_4.addWidget(self.box_Cooling_Class, 9, 2, 1, 1)
        self.i_ct_pocket_H = QtWidgets.QLineEdit(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_ct_pocket_H.sizePolicy().hasHeightForWidth())
        self.i_ct_pocket_H.setSizePolicy(sizePolicy)
        self.i_ct_pocket_H.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_ct_pocket_H.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_ct_pocket_H.setFrame(False)
        self.i_ct_pocket_H.setObjectName("i_ct_pocket_H")
        self.gridLayout_4.addWidget(self.i_ct_pocket_H, 12, 2, 1, 1)
        self.i_ct_pocket_H0 = QtWidgets.QLineEdit(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_ct_pocket_H0.sizePolicy().hasHeightForWidth())
        self.i_ct_pocket_H0.setSizePolicy(sizePolicy)
        self.i_ct_pocket_H0.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_ct_pocket_H0.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_ct_pocket_H0.setFrame(False)
        self.i_ct_pocket_H0.setObjectName("i_ct_pocket_H0")
        self.gridLayout_4.addWidget(self.i_ct_pocket_H0, 13, 2, 1, 1)
        self.label_CT_Groups = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CT_Groups.sizePolicy().hasHeightForWidth())
        self.label_CT_Groups.setSizePolicy(sizePolicy)
        self.label_CT_Groups.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_CT_Groups.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_CT_Groups.setObjectName("label_CT_Groups")
        self.gridLayout_4.addWidget(self.label_CT_Groups, 3, 0, 1, 1)
        self.label_H0_Pocket_Lgth = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_H0_Pocket_Lgth.sizePolicy().hasHeightForWidth())
        self.label_H0_Pocket_Lgth.setSizePolicy(sizePolicy)
        self.label_H0_Pocket_Lgth.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_H0_Pocket_Lgth.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_H0_Pocket_Lgth.setObjectName("label_H0_Pocket_Lgth")
        self.gridLayout_4.addWidget(self.label_H0_Pocket_Lgth, 13, 1, 1, 1)
        self.i_HV_voltage = QtWidgets.QLineEdit(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_HV_voltage.sizePolicy().hasHeightForWidth())
        self.i_HV_voltage.setSizePolicy(sizePolicy)
        self.i_HV_voltage.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_HV_voltage.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_HV_voltage.setFrame(False)
        self.i_HV_voltage.setObjectName("i_HV_voltage")
        self.gridLayout_4.addWidget(self.i_HV_voltage, 5, 2, 1, 1)
        self.label_Transformer_kVA = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Transformer_kVA.sizePolicy().hasHeightForWidth())
        self.label_Transformer_kVA.setSizePolicy(sizePolicy)
        self.label_Transformer_kVA.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_Transformer_kVA.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Transformer_kVA.setObjectName("label_Transformer_kVA")
        self.gridLayout_4.addWidget(self.label_Transformer_kVA, 4, 0, 1, 1)
        self.o_HV_amps = QtWidgets.QLineEdit(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_HV_amps.sizePolicy().hasHeightForWidth())
        self.o_HV_amps.setSizePolicy(sizePolicy)
        self.o_HV_amps.setMaximumSize(QtCore.QSize(100, 16777215))
        self.o_HV_amps.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);")
        self.o_HV_amps.setText("")
        self.o_HV_amps.setFrame(False)
        self.o_HV_amps.setObjectName("o_HV_amps")
        self.gridLayout_4.addWidget(self.o_HV_amps, 6, 2, 1, 1)
        self.i_ct_groups_qty = QtWidgets.QLineEdit(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_ct_groups_qty.sizePolicy().hasHeightForWidth())
        self.i_ct_groups_qty.setSizePolicy(sizePolicy)
        self.i_ct_groups_qty.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_ct_groups_qty.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_ct_groups_qty.setFrame(False)
        self.i_ct_groups_qty.setObjectName("i_ct_groups_qty")
        self.gridLayout_4.addWidget(self.i_ct_groups_qty, 3, 2, 1, 1)
        self.i_frequency = QtWidgets.QLineEdit(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_frequency.sizePolicy().hasHeightForWidth())
        self.i_frequency.setSizePolicy(sizePolicy)
        self.i_frequency.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_frequency.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_frequency.setFrame(False)
        self.i_frequency.setObjectName("i_frequency")
        self.gridLayout_4.addWidget(self.i_frequency, 10, 2, 1, 1)
        self.label_Frequency = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Frequency.sizePolicy().hasHeightForWidth())
        self.label_Frequency.setSizePolicy(sizePolicy)
        self.label_Frequency.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_Frequency.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Frequency.setObjectName("label_Frequency")
        self.gridLayout_4.addWidget(self.label_Frequency, 10, 0, 1, 1)
        self.label_HV_Voltage_3 = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_HV_Voltage_3.sizePolicy().hasHeightForWidth())
        self.label_HV_Voltage_3.setSizePolicy(sizePolicy)
        self.label_HV_Voltage_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_HV_Voltage_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_HV_Voltage_3.setObjectName("label_HV_Voltage_3")
        self.gridLayout_4.addWidget(self.label_HV_Voltage_3, 5, 0, 1, 1)
        self.label_Cooling_Class = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Cooling_Class.sizePolicy().hasHeightForWidth())
        self.label_Cooling_Class.setSizePolicy(sizePolicy)
        self.label_Cooling_Class.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_Cooling_Class.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Cooling_Class.setObjectName("label_Cooling_Class")
        self.gridLayout_4.addWidget(self.label_Cooling_Class, 9, 0, 1, 1)
        self.i_transformer_kVA = QtWidgets.QLineEdit(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_transformer_kVA.sizePolicy().hasHeightForWidth())
        self.i_transformer_kVA.setSizePolicy(sizePolicy)
        self.i_transformer_kVA.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_transformer_kVA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_transformer_kVA.setFrame(False)
        self.i_transformer_kVA.setObjectName("i_transformer_kVA")
        self.gridLayout_4.addWidget(self.i_transformer_kVA, 4, 2, 1, 1)
        self.label_CT_pocket_Lgth = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CT_pocket_Lgth.sizePolicy().hasHeightForWidth())
        self.label_CT_pocket_Lgth.setSizePolicy(sizePolicy)
        self.label_CT_pocket_Lgth.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_CT_pocket_Lgth.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_CT_pocket_Lgth.setObjectName("label_CT_pocket_Lgth")
        self.gridLayout_4.addWidget(self.label_CT_pocket_Lgth, 12, 0, 2, 1)
        self.i_LV_voltage = QtWidgets.QLineEdit(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_LV_voltage.sizePolicy().hasHeightForWidth())
        self.i_LV_voltage.setSizePolicy(sizePolicy)
        self.i_LV_voltage.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_LV_voltage.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_LV_voltage.setFrame(False)
        self.i_LV_voltage.setObjectName("i_LV_voltage")
        self.gridLayout_4.addWidget(self.i_LV_voltage, 7, 2, 1, 1)
        self.label_HV_Amps = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_HV_Amps.sizePolicy().hasHeightForWidth())
        self.label_HV_Amps.setSizePolicy(sizePolicy)
        self.label_HV_Amps.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_HV_Amps.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_HV_Amps.setObjectName("label_HV_Amps")
        self.gridLayout_4.addWidget(self.label_HV_Amps, 6, 0, 1, 1)
        self.o_LV_amps = QtWidgets.QLineEdit(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_LV_amps.sizePolicy().hasHeightForWidth())
        self.o_LV_amps.setSizePolicy(sizePolicy)
        self.o_LV_amps.setMaximumSize(QtCore.QSize(100, 16777215))
        self.o_LV_amps.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);")
        self.o_LV_amps.setText("")
        self.o_LV_amps.setFrame(False)
        self.o_LV_amps.setObjectName("o_LV_amps")
        self.gridLayout_4.addWidget(self.o_LV_amps, 8, 2, 1, 1)
        self.label_LV_Amps = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_LV_Amps.sizePolicy().hasHeightForWidth())
        self.label_LV_Amps.setSizePolicy(sizePolicy)
        self.label_LV_Amps.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_LV_Amps.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_LV_Amps.setObjectName("label_LV_Amps")
        self.gridLayout_4.addWidget(self.label_LV_Amps, 8, 0, 1, 1)
        self.label_HV_Voltage = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_HV_Voltage.sizePolicy().hasHeightForWidth())
        self.label_HV_Voltage.setSizePolicy(sizePolicy)
        self.label_HV_Voltage.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_HV_Voltage.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_HV_Voltage.setObjectName("label_HV_Voltage")
        self.gridLayout_4.addWidget(self.label_HV_Voltage, 7, 0, 1, 1)
        self.label_H_Pocket_Lgth = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_H_Pocket_Lgth.sizePolicy().hasHeightForWidth())
        self.label_H_Pocket_Lgth.setSizePolicy(sizePolicy)
        self.label_H_Pocket_Lgth.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_H_Pocket_Lgth.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_H_Pocket_Lgth.setObjectName("label_H_Pocket_Lgth")
        self.gridLayout_4.addWidget(self.label_H_Pocket_Lgth, 12, 1, 1, 1)
        self.frame_packings_3 = QtWidgets.QFrame(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_packings_3.sizePolicy().hasHeightForWidth())
        self.frame_packings_3.setSizePolicy(sizePolicy)
        self.frame_packings_3.setStyleSheet("QFrame {\n"
"    border-radius: 6px; /* Slightly rounded corners */\n"
" \n"
"    background-color: transparent; /* Keeps original background */\n"
"    color: (0,0,0);     \n"
"}\n"
"QLabel {\n"
"    color: black; /* Set text color */\n"
"\n"
"}\n"
"")
        self.frame_packings_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_packings_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_packings_3.setObjectName("frame_packings_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_packings_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_4.addWidget(self.frame_packings_3, 11, 2, 1, 1)
        self.label_SO = QtWidgets.QLabel(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SO.sizePolicy().hasHeightForWidth())
        self.label_SO.setSizePolicy(sizePolicy)
        self.label_SO.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_SO.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_SO.setObjectName("label_SO")
        self.gridLayout_4.addWidget(self.label_SO, 1, 0, 2, 1)
        self.i_so = QtWidgets.QLineEdit(parent=self.FRAME_GENERAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_so.sizePolicy().hasHeightForWidth())
        self.i_so.setSizePolicy(sizePolicy)
        self.i_so.setMaximumSize(QtCore.QSize(100, 16777215))
        self.i_so.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.i_so.setFrame(False)
        self.i_so.setObjectName("i_so")
        self.gridLayout_4.addWidget(self.i_so, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.FRAME_GENERAL, 2, 0, 1, 1)
        self.input_CT_ScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.input_CT_ScrollArea, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/current-transformer.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tab_main_widget.addTab(self.tabTransformer, icon2, "")
        self.tab_DRAW_CONTACTS = QtWidgets.QWidget()
        self.tab_DRAW_CONTACTS.setObjectName("tab_DRAW_CONTACTS")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_DRAW_CONTACTS)
        self.gridLayout_12.setObjectName("gridLayout_12")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/TEMPLATE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tab_main_widget.addTab(self.tab_DRAW_CONTACTS, icon3, "")
        self.tab_DRAW_LV_CTS = QtWidgets.QWidget()
        self.tab_DRAW_LV_CTS.setObjectName("tab_DRAW_LV_CTS")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/SWITCH.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tab_main_widget.addTab(self.tab_DRAW_LV_CTS, icon4, "")
        self.gridLayout_23.addWidget(self.tab_main_widget, 1, 0, 1, 1)
        self.gridLayout_25.addWidget(self.Main_frame, 1, 0, 1, 1)
        EasyConnectACAD.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=EasyConnectACAD)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1424, 46))
        self.menubar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setStyleSheet("/* ======== QMenuBar (Barra de Menús) ======== */\n"
"QMenuBar {\n"
"    background-color: rgb(30, 40, 49);\n"
"    color: white;\n"
"    border-radius: 8px;  /* Bordes redondeados */\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 6px 20px;  /* Espaciado interno */\n"
"    margin: 5px;  /* Separación entre elementos */\n"
"    border-radius: 6px;  /* Bordes redondeados */\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* Hover con transparencia */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* ======== QMenu (Menú Desplegable) ======== */\n"
"QMenu {\n"
"    background-color: rgb(30, 40, 49);\n"
"    color: white;\n"
"    border-radius: 8px;  /* Bordes redondeados */\n"
"    padding: 6px 20px;\n"
"}\n"
"\n"
"/* Opciones dentro del menú */\n"
"QMenu::item {\n"
"    padding: 6px 50px;\n"
"    margin: 2px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Efecto hover con transparencia y sin tapar la letra */\n"
"QMenu::item:selected {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    border-radius: 6px;\n"
"}")
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(parent=self.menubar)
        self.menuOpen.setAutoFillBackground(False)
        self.menuOpen.setStyleSheet("")
        self.menuOpen.setObjectName("menuOpen")
        EasyConnectACAD.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=EasyConnectACAD)
        self.statusbar.setObjectName("statusbar")
        EasyConnectACAD.setStatusBar(self.statusbar)
        self.actionDistribution_3PH = QtGui.QAction(parent=EasyConnectACAD)
        self.actionDistribution_3PH.setIconVisibleInMenu(True)
        self.actionDistribution_3PH.setObjectName("actionDistribution_3PH")
        self.actionDistribution_1PH = QtGui.QAction(parent=EasyConnectACAD)
        self.actionDistribution_1PH.setObjectName("actionDistribution_1PH")
        self.actionOpen_ACAD = QtGui.QAction(parent=EasyConnectACAD)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionOpen_ACAD.setIcon(icon5)
        self.actionOpen_ACAD.setObjectName("actionOpen_ACAD")
        self.action = QtGui.QAction(parent=EasyConnectACAD)
        self.action.setObjectName("action")
        self.actionSelect_Multiple_quotes_for_3PH = QtGui.QAction(parent=EasyConnectACAD)
        self.actionSelect_Multiple_quotes_for_3PH.setObjectName("actionSelect_Multiple_quotes_for_3PH")
        self.actionSelect_Multiple_quotes_for_3PH_DB = QtGui.QAction(parent=EasyConnectACAD)
        self.actionSelect_Multiple_quotes_for_3PH_DB.setObjectName("actionSelect_Multiple_quotes_for_3PH_DB")
        self.actionImport_3PH_2 = QtGui.QAction(parent=EasyConnectACAD)
        self.actionImport_3PH_2.setObjectName("actionImport_3PH_2")
        self.actionImport_1PH_2 = QtGui.QAction(parent=EasyConnectACAD)
        self.actionImport_1PH_2.setObjectName("actionImport_1PH_2")
        self.actionGen_Rep = QtGui.QAction(parent=EasyConnectACAD)
        self.actionGen_Rep.setObjectName("actionGen_Rep")
        self.actionEXCEL_2_PDF = QtGui.QAction(parent=EasyConnectACAD)
        self.actionEXCEL_2_PDF.setObjectName("actionEXCEL_2_PDF")
        self.actionSelect_Multiple_Quotes_for_1PH = QtGui.QAction(parent=EasyConnectACAD)
        self.actionSelect_Multiple_Quotes_for_1PH.setObjectName("actionSelect_Multiple_Quotes_for_1PH")
        self.actionGen_Rep_1PH = QtGui.QAction(parent=EasyConnectACAD)
        self.actionGen_Rep_1PH.setObjectName("actionGen_Rep_1PH")
        self.action_import_excel_3PH = QtGui.QAction(parent=EasyConnectACAD)
        self.action_import_excel_3PH.setObjectName("action_import_excel_3PH")
        self.action_import_excel_1PH = QtGui.QAction(parent=EasyConnectACAD)
        self.action_import_excel_1PH.setObjectName("action_import_excel_1PH")
        self.actionGenerateReport3PH = QtGui.QAction(parent=EasyConnectACAD)
        self.actionGenerateReport3PH.setObjectName("actionGenerateReport3PH")
        self.actionGenerateReport1PH = QtGui.QAction(parent=EasyConnectACAD)
        self.actionGenerateReport1PH.setObjectName("actionGenerateReport1PH")
        self.action_draw_3PH_scaled = QtGui.QAction(parent=EasyConnectACAD)
        self.action_draw_3PH_scaled.setObjectName("action_draw_3PH_scaled")
        self.action_draw_1PH_scaled = QtGui.QAction(parent=EasyConnectACAD)
        self.action_draw_1PH_scaled.setObjectName("action_draw_1PH_scaled")
        self.action_draw_ZIGZAG_scaled = QtGui.QAction(parent=EasyConnectACAD)
        self.action_draw_ZIGZAG_scaled.setObjectName("action_draw_ZIGZAG_scaled")
        self.menuOpen.addAction(self.actionOpen_ACAD)
        self.menubar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(EasyConnectACAD)
        self.tab_main_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EasyConnectACAD)

    def retranslateUi(self, EasyConnectACAD):
        _translate = QtCore.QCoreApplication.translate
        EasyConnectACAD.setWindowTitle(_translate("EasyConnectACAD", "TransformerAutomation"))
        self.label_footer.setToolTip(_translate("EasyConnectACAD", "THIS APP IS EXCLUSIVE FOR PTI TRANSFORMERS"))
        self.label_footer.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-size:6pt; color:#b6b6b6;\">Done by: Juan Gomez</span></p></body></html>"))
        self.label_TITLE_EasyConnect.setText(_translate("EasyConnectACAD", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">EASY CONNECT</span></p></body></html>"))
        self.box_CTH1_Application.setItemText(0, _translate("EasyConnectACAD", "PREDEFINED"))
        self.box_CTH1_Application.setItemText(1, _translate("EasyConnectACAD", "LDC"))
        self.box_CTH1_Application.setItemText(2, _translate("EasyConnectACAD", "WTI"))
        self.box_CTH1_bushing_angled.setItemText(0, _translate("EasyConnectACAD", "YES"))
        self.box_CTH1_bushing_angled.setItemText(1, _translate("EasyConnectACAD", "NO"))
        self.label_CT_Type.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">CT TYPE</span></p></body></html>"))
        self.label_Bushing_Angled.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">IS BUSHING ANGLED?</span></p></body></html>"))
        self.label_CT_Application.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">CT APPLICATION</span></p></body></html>"))
        self.label_Tag_Individual.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">TAG INDIVIDUAL</span></p></body></html>"))
        self.label_Bushing_OD.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">BUSHING OD [in]</span></p></body></html>"))
        self.label_Thermal_Factor.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">THERMAL FACTOR [ 95°C ]</span></p></body></html>"))
        self.label_Ratio_Override.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">RATIO OVERRIDE</span></p></body></html>"))
        self.label_CT_Height_Override.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">CT HEIGHT OVERRIDE</span></p></body></html>"))
        self.label_Ratio_Type.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">RATIO TYPE</span></p></body></html>"))
        item = self.tableCTHigh.verticalHeaderItem(0)
        item.setText(_translate("EasyConnectACAD", "CT / PH"))
        item = self.tableCTHigh.horizontalHeaderItem(0)
        item.setText(_translate("EasyConnectACAD", "H0"))
        item = self.tableCTHigh.horizontalHeaderItem(1)
        item.setText(_translate("EasyConnectACAD", "H1"))
        item = self.tableCTHigh.horizontalHeaderItem(2)
        item.setText(_translate("EasyConnectACAD", "H2"))
        item = self.tableCTHigh.horizontalHeaderItem(3)
        item.setText(_translate("EasyConnectACAD", "H3"))
        __sortingEnabled = self.tableCTHigh.isSortingEnabled()
        self.tableCTHigh.setSortingEnabled(False)
        self.tableCTHigh.setSortingEnabled(__sortingEnabled)
        self.label_Accuracy_Override.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">ACCURACY OVERRIDE</span></p></body></html>"))
        self.i_Bushing_OD.setText(_translate("EasyConnectACAD", "4"))
        self.box_CTH1_Type.setItemText(0, _translate("EasyConnectACAD", "PROTECTION"))
        self.box_CTH1_Type.setItemText(1, _translate("EasyConnectACAD", "METERING"))
        self.label_STD.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">STANDARD</span></p></body></html>"))
        self.label_Notes.setText(_translate("EasyConnectACAD", "<html><head/><body><p>NOTES</p></body></html>"))
        self.box_CTH1_STD.setItemText(0, _translate("EasyConnectACAD", "CSA"))
        self.box_CTH1_STD.setItemText(1, _translate("EasyConnectACAD", "ANSI"))
        self.box_CTH1_STD.setItemText(2, _translate("EasyConnectACAD", "IEC"))
        self.label_Tag.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">CT TAG</span></p></body></html>"))
        self.i_CTH1_tag.setText(_translate("EasyConnectACAD", "CTH"))
        self.title_General_Info.setText(_translate("EasyConnectACAD", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">GENERAL INFORMATION</span></p></body></html>"))
        self.title_CTH_INPUTS.setText(_translate("EasyConnectACAD", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">HV CTH INPUTS</span></p></body></html>"))
        self.box_Cooling_Class.setItemText(0, _translate("EasyConnectACAD", "PREDEFINED"))
        self.box_Cooling_Class.setItemText(1, _translate("EasyConnectACAD", "LDC"))
        self.box_Cooling_Class.setItemText(2, _translate("EasyConnectACAD", "WTI"))
        self.i_ct_pocket_H.setText(_translate("EasyConnectACAD", "60"))
        self.i_ct_pocket_H0.setText(_translate("EasyConnectACAD", "60"))
        self.label_CT_Groups.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">CT GROUPS</span></p></body></html>"))
        self.label_H0_Pocket_Lgth.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">H0</span></p></body></html>"))
        self.i_HV_voltage.setText(_translate("EasyConnectACAD", "69000"))
        self.label_Transformer_kVA.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">TRANSFORMER kVA</span></p></body></html>"))
        self.i_ct_groups_qty.setText(_translate("EasyConnectACAD", "2"))
        self.i_frequency.setText(_translate("EasyConnectACAD", "60"))
        self.label_Frequency.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">FREQUENCY</span></p></body></html>"))
        self.label_HV_Voltage_3.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">HV VOLTAGE</span></p></body></html>"))
        self.label_Cooling_Class.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">COOLING CLASS</span></p></body></html>"))
        self.i_transformer_kVA.setText(_translate("EasyConnectACAD", "18700"))
        self.label_CT_pocket_Lgth.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">CT POCKET LENGTH</span></p></body></html>"))
        self.i_LV_voltage.setText(_translate("EasyConnectACAD", "12470"))
        self.label_HV_Amps.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">HV AMPS</span></p></body></html>"))
        self.label_LV_Amps.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">LV AMPS</span></p></body></html>"))
        self.label_HV_Voltage.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">LV VOLTAGE</span></p></body></html>"))
        self.label_H_Pocket_Lgth.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">H</span></p></body></html>"))
        self.label_SO.setText(_translate("EasyConnectACAD", "<html><head/><body><p><span style=\" font-weight:600;\">SO</span></p></body></html>"))
        self.i_so.setText(_translate("EasyConnectACAD", "22154"))
        self.tab_main_widget.setTabText(self.tab_main_widget.indexOf(self.tabTransformer), _translate("EasyConnectACAD", "DRAW CT\'S HV"))
        self.tab_main_widget.setTabText(self.tab_main_widget.indexOf(self.tab_DRAW_CONTACTS), _translate("EasyConnectACAD", "DRAW CT\'S LV"))
        self.tab_main_widget.setTabText(self.tab_main_widget.indexOf(self.tab_DRAW_LV_CTS), _translate("EasyConnectACAD", "DRAW CONTACTS"))
        self.menuOpen.setTitle(_translate("EasyConnectACAD", "File"))
        self.actionDistribution_3PH.setText(_translate("EasyConnectACAD", "Find Excel"))
        self.actionDistribution_1PH.setText(_translate("EasyConnectACAD", "Distribution 1PH"))
        self.actionOpen_ACAD.setText(_translate("EasyConnectACAD", " Open ACAD"))
        self.action.setText(_translate("EasyConnectACAD", "06-XXXXX-WS_INP-CCC"))
        self.actionSelect_Multiple_quotes_for_3PH.setText(_translate("EasyConnectACAD", "Select Multiple quotes for 3PH"))
        self.actionSelect_Multiple_quotes_for_3PH_DB.setText(_translate("EasyConnectACAD", "Select Multiple quotes for 3PH Dual Voltage"))
        self.actionImport_3PH_2.setText(_translate("EasyConnectACAD", "IMPORT DESIGN"))
        self.actionImport_1PH_2.setText(_translate("EasyConnectACAD", "IMPORT DESIGN"))
        self.actionGen_Rep.setText(_translate("EasyConnectACAD", "06-XXXXX-WS_INP-CCC"))
        self.actionEXCEL_2_PDF.setText(_translate("EasyConnectACAD", "EXCEL 2 PDF"))
        self.actionSelect_Multiple_Quotes_for_1PH.setText(_translate("EasyConnectACAD", "Select Multiple Quotes for 1PH Master"))
        self.actionGen_Rep_1PH.setText(_translate("EasyConnectACAD", "06-XXXXX-WS_INP-CCC"))
        self.action_import_excel_3PH.setText(_translate("EasyConnectACAD", "IMPORT DESIGN"))
        self.action_import_excel_1PH.setText(_translate("EasyConnectACAD", "IMPORT DESIGN"))
        self.actionGenerateReport3PH.setText(_translate("EasyConnectACAD", "06-XXXXX-WS_INP-CCC"))
        self.actionGenerateReport1PH.setText(_translate("EasyConnectACAD", "06-XXXXX-WS_INP-CCC"))
        self.action_draw_3PH_scaled.setText(_translate("EasyConnectACAD", "3 PHASE MASTER"))
        self.action_draw_1PH_scaled.setText(_translate("EasyConnectACAD", "1 PH MASTER"))
        self.action_draw_ZIGZAG_scaled.setText(_translate("EasyConnectACAD", "ZIG-ZAG"))
